
%%
csvwrite_with_headers(strcat('./Export/problem2plots_opt.csv'),...
      [t',u,x1,x3],...
      {'t','u','lambda','p'},0,0);
  
%%
csvwrite_with_headers(strcat('./Export/problem2plots_q_0.1_opt.csv'),...
      [t',u,x1,x3],...
      {'t','u','lambda','p'},0,0);
%%
csvwrite_with_headers(strcat('./Export/problem2plots_q_1.0_opt.csv'),...
      [t',u,x1,x3],...
      {'t','u','lambda','p'},0,0);
%%
csvwrite_with_headers(strcat('./Export/problem2plots_q_10_opt.csv'),...
      [t',u,x1,x3],...
      {'t','u','lambda','p'},0,0);

%%
csvwrite_with_headers(strcat('./Export/problem4plots_opt.csv'),...
      [t',u1,u2,x1,x3,x5],...
      {'t','u1','u2','lambda','p','e'},0,0);

%%
csvwrite_with_headers(strcat('./Export/problem4plots_ed_1_lambdad_1_opt.csv'),...
      [t',u1,u2,x1,x3,x5],...
      {'t','u1','u2','lambda','p','e'},0,0);

%%
csvwrite_with_headers(strcat('./Export/problem4plots_ed_1_pd_1_opt.csv'),...
      [t',u1,u2,x1,x3,x5],...
      {'t','u1','u2','lambda','p','e'},0,0);